### ISSUE TITLE
The README should give the API of the library

### ISSUE THREAD

**Issue by stefanheule** [p4lang/p4-constraints#18]
Right now it's not clear how one would use the library :)

**Comment by stefanheule** [comment]
Even worse, it is incredibly hard to find the actual API. We should make this much more discover-able.

**Comment by smolkaj** [comment]
Action items:
* Explain public API in README.
* Link to @stefanheule's slides in the README?
* Ideally, generated HTML documentation of public API from source code and insert a link in README.

**Comment by smolkaj** [comment]
@stefanheule can we close this? The last two action items seem impossible/hard to do at the moment, and the status quo  seems quite acceptable.

**Comment by smolkaj** [comment]
I'll close we don't know how to address the remaining action items.
