### ISSUE TITLE
Make working with booleans nicer.

### ISSUE THREAD

**Issue by smolkaj** [p4lang/p4-constraints#26]
The following example from the [language-specification](docs/language-specification.md) is kind of awkward:
```p4
@entry_restriction("ipv4.valid == 1")
table ipv4_table {
  key = {
    ipv4.isValid() : exact @name("ipv4.valid");
    ipv4.dst : ternary;
  }
}
```
Since `ipv4.isValid()` is of type `bool` in P4, it would be more natural to write
```p4
@entry_restriction("ipv4.valid == true")
```
or just
```p4
@entry_restriction("ipv4.valid")
```

From a technical perspective, the difficulty is that `ipv4.valid` is of type `bit<1>` as far as p4info (and thus, p4-constraints) is concerned; p4-constraints simply does not know that this used to be a `bool` in P4 land.

Maybe this is information that we could consider adding to p4info? It seems like this may be useful for P4Runtime for pretty printing? @stefanheule @antoninbas 

As a workaround, I briefly considered adding an implicit cast `bit<1> ~> bool`. However, we already have an implicit cast `int ~> bit<W>` and so by transitivity this would give us `int ~> bool`. I feel strongly that this is not what we want, as it would make `@entry_restriction("42")` a valid constraint.

**Comment by jnfoster** [comment]
Ugh. This is a wart that dates back to P4_14 times and has frustrated me for a long time... I don't have a solution but maybe we can nudge the LDWG and API WGs to make it more coherent.

**Comment by stefanheule** [comment]
Yeah this looks like a deeper issue we alone can't fix. I agree with everything Steffen and Nate are saying!

**Comment by smolkaj** [comment]
The best solution to this problem would be for P4Runtime to distinguish between `bool` and `bit<1>`. What are our options without getting help from P4Runtime, though?

As discussed above, solving the issue by adding an implicit conversion bit<1> ~> bool will mean we will either
* have to make int ~> bool a legal implicit conversion, too, which makes "42" a valid constraint; or
* break transitivity of implicit conversions.

Here is an alternative proposal that does not rely on implicit conversions. The idea is to instead introduce a type trait "boolable" that allows to interpret values of certain types as booleans. The only boolable types would be bool and bit<1>. We would then generalize the boolean operators `!`, `||`, `&&`, etc. to allow arguments of trait boolable. Importantly, the type trait boolable would not be closed under implicit conversions, i.e. bit<1> would be boolable but int would not be even though we have int ~> bit<1>.

In the words of Haskell:
```
class Boolable a where
  interpretAsBool :: a -> bool

instance Boolable bool where
  interpretAsBool b = b

instance Boolable bit<1> where
  interpretAsBool 1 = True
  interpretAsBool 0 = False
```
The boolean operators are then generalized to take Boolables instead of bools:
```
! : Boolable a => a -> bool
|| : Boolable a, Boolable b => a -> b -> bool
```
etc.

Let me know if you have any feedback on this idea @stefanheule @jnfoster. Thanks :)
