### ISSUE TITLE
Constraint error handling

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4-constraints#86]
Two quick questions on the constraint scope and satisfiability handling. 

1. As far as I understand, the scope of an `entry_restriction` only extends to the object it is attached to. Is that right? For example, if I have a constraint where

```
@entry_restriction("
  // Only match on IPv6 addresses of IPv6 packets.
  hdr.ipv6.dst_addr::mask != 0 ->
    hdr.ethernet.ether_type == IPv6_ETHER_TYPE;
")
table acl_table {
  key = {
    hdr.ethernet.ether_type : ternary;
  }
  actions = { ... }
}
```
where the referenced key does not exist, will this throw an error?

2. Similarly, what is the expected behavior when the constraint is simply unsatisfiable (either because of a conflict or a plain `false`). Is the expectation that only the default action can be taken and no entry can be inserted? Or is this an error in the declaration of the constraint?

**Comment by fruffy** [comment]
Great thanks! 

Another question: Is `@refers_to` part of constraints? I was only able to find this discussion on it: 
https://github.com/p4lang/p4c/issues/2629

**Comment by smolkaj** [comment]
`@refers_to` is another form of constraint we use, but not technically part of "p4-constraints".
Unfortunately there is no public documentation.

It is a essentially an existential constraint across multiple tables.
If you have an entry with a value `x` that `@refers_to(table_name, match_field)`, then there must also exist another table entry in `table_name` where `match_field` has value `x` (otherwise our switch would reject the first entry).

**Comment by fruffy** [comment]
Thanks!

**Comment by jonathan-dilorenzo** [comment]
Additionally, there may be multiple `refers_to` annotations on the same "referencer" table (in its action or key) that refer to the same "referencee" table. E.g. consider an action with two parameters like so:
```
@refers_to(table_a, key_1) some_type param_1
@refers_to(table_a, key_2) some_type param_2
```

Here the `refers_to` annotations on `param_1` and `param_2` both refer to `table_a`. In this case, both values (for `key_1` and `key_2`) must exist in a single entry in `table_a` (as opposed to potentially referring to two different entries).
