### ISSUE TITLE
Support "@action_restriction"

### ISSUE THREAD

**Issue by smolkaj** [p4lang/p4-constraints#98]
It would be nice to support constraints on actions as well.
These constraints would be inherited by any table using the action.

This is related to but distinct from https://github.com/p4lang/p4-constraints/issues/99, which is about constraining actions within an `@table_restriction`.

@jonathan-dilorenzo @kheradmandG @rhalstea @verios-google for visibility

**Comment by jonathan-dilorenzo** [comment]
Yeah, nice idea. Is there a particular use case you had in mind? There was one design we had where it would have been useful to constrain two parameters to be equal (due to odd and fairly convoluted reasons) though we eventually came up with a workaround that avoided this.

**Comment by smolkaj** [comment]
I have a use case where an integer parameter should be nonzero, due to https://github.com/opencomputeproject/SAI/blob/master/bm/p4-sai/docs/simple_switch.md:
 > mcast_grp: needed for the multicast feature. This field needs to be written in the ingress pipeline when you wish the packet to be multicast. A value of 0 means no multicast. This value must be one of a valid multicast group configured through bmv2 runtime interfaces.

**Comment by AkashKumar7902** [comment]
Is this issue up for takes ?

**Comment by Sanket-0510** [comment]
Hey I would like to work over this

**Comment by Bakugo90** [comment]
Hello @smolkaj , @jonathan-dilorenzo ,

Greetings everyone !
My name is Samdou Ouro-agorouko. Currently undergrad student in Physics, I'm passionate about computers science. I find machine and low-level language very fascinating. [Here](https://github.com/Bakugo90/alx-low_level_programming) is an example of a repo where I have published what I have learnt myself about C. I also have a bit contribute to low level system language , you can see my contributions at https://github.com/ThinkOpenly/sail-riscv/pull/8
I am interested in pursuing p4 constraints project under the GSOC.

Happy to be here with you all

**Comment by smolkaj** [comment]
Hey everyone, thanks for reaching out!
This issue was solved already, but we have another exciting project to work on as part of the Google Summer of Code, namely project #2 here: https://docs.google.com/document/d/1op0ZFAix3qGYMaK3KMJe1qy-L8BrK3vf22a2CdLy1vw/edit?usp=sharing

**Comment by Sanket-0510** [comment]
Hey @smolkaj  greetings!
I tried reaching out to the mentors regarding GSOC mentorship and the projects but could not do so, can you please share the communication channel where I can find the team and mentor for further doubts and discussions on the project proposal

Regards,
Sanket

**Comment by smolkaj** [comment]
Looping in @qobilidop, he serves at the central point of contact.

**Comment by qobilidop** [comment]
Hi @Sanket-0510,

You can CC me in the email and I can try to help you get in contact with the mentors for the specific projects you are interested in.

As to communication channels, you can take a look at our Contributor Guidance (find the link in our [GSoC org profile](https://summerofcode.withgoogle.com/programs/2024/organizations/the-p4-language-consortium)).

**Comment by Sanket-0510** [comment]
> Hi @Sanket-0510,
> 
> You can CC me in the email and I can try to help you get in contact with the mentors for the specific projects you are interested in.
> 
> As to communication channels, you can take a look at our Contributor Guidance (find the link in our [GSoC org profile](https://summerofcode.withgoogle.com/programs/2024/organizations/the-p4-language-consortium)).

Sure I have mailed mentors personally but from next time onwards I would add you in the cc for sure, I will mail you and respective mentors my research which I have done over the extension project , thank you so much.
Regards,
Sanket.
